	
curr_date=`date +"%A, %B %d, %Y"`
curr_time=`date +"%H:%M"`
timezone_host=`date +"%:::z %Z"`
host_type=`dmidecode -t 3 | grep Type | awk '{print $2}'`
host_manufacturer=`dmidecode -s system-manufacturer`
host_product_name=`dmidecode -s baseboard-product-name`
host_version=`dmidecode -s system-version`
host_serial_number=`dmidecode -s system-serial-number`
host_system_family=`dmidecode -s system-family`
host_bios_vendor=`dmidecode -s bios-vendor`
bios_date=`date +"%A, %B %d, %Y"`
bios_date_formated=`date +"%4Y-%m-%d"`
bios_time=`date +"%H:%M"`
host_timeZone=`date +"%:::z %Z"`
datetime_host=`date +"%4Y-%m-%d %H:%M %:::z %Z"`
datetime_utc0=`date -u +"%4Y-%m-%d %H:%M %:::z %Z"`
evid_dev_model=`hdparm -I /dev/$evid_dev 2>/dev/null | grep -i 'Model Number' | awk '{print $3" "$4" "$5" "$6}'`
evid_dev_serial=`hdparm -I /dev/$evid_dev 2>/dev/null | grep -i 'Serial Number' | awk '{print $3" "$4" "$5" "$6}'`
evid_dev_firmware=`hdparm -I /dev/$evid_dev 2>/dev/null | grep -i 'Firmware Revision' | awk '{print $3" "$4" "$5" "$6}'`
LBASectors=`hdparm -g /dev/$evid_dev | awk -F'[=,]' '{print $4}'`
evid_sectors=`echo $LBASectors | awk '{print $1}'`
evid_bytes=`fdisk -l -u /dev/$evid_dev | grep $evid_dev | grep bytes | awk '{print $5}'`
evid_size=`fdisk -l -u /dev/$evid_dev | grep Disk | grep $evid_dev | awk -F ',' '{ print $1}' | awk '{print $3$4}'`
evid_part_count=`fdisk -l -u /dev/$evid_dev | grep $evid_dev | grep -v Disk | wc -l`
evid_part1_field2=`fdisk -l -u /dev/$evid_dev | grep -A1 Device | grep $evid_dev'1' | awk '{print $2}'`
evid_part1_field3=`fdisk -l -u /dev/$evid_dev | grep -A1 Device | grep $evid_dev'1' | awk '{print $3}'`
evid_part2_field2=`fdisk -l -u /dev/$evid_dev | grep -A2 Device | grep $evid_dev'2' | awk '{print $2}'`
evid_part2_field3=`fdisk -l -u /dev/$evid_dev | grep -A2 Device | grep $evid_dev'2' | awk '{print $3}'`
tgt_dev_model=`hdparm -I /dev/$tgt_dev | grep -i 'Model Number' | awk '{print $3" "$4" "$5" "$6}'`
tgt_dev_serial=`hdparm -I /dev/$tgt_dev | grep -i 'Serial Number' | awk '{print $3" "$4" "$5" "$6}'`
tgt_dev_firmware=`hdparm -I /dev/$tgt_dev | grep -i 'Firmware Revision' | awk '{print $3" "$4" "$5" "$6}'`
tgt_act_mnt=`df -h -P | grep $tgt_mnt | awk {'print $6'}`
tgt_scsi_vendor=`cat /proc/scsi/scsi | grep -A 1 "scsi$tgt_dev_id" | grep "Vendor" | awk -F ':' '{print $2}'`
tgt_scsi_model=`cat /proc/scsi/scsi | grep -A 1 "scsi$tgt_dev_id" | grep "Vendor" | awk -F ':' '{print $3}' | awk -F 'Rev' '{print $1}'`
tgt_scsi_serial=`lshw -C Disk | grep -A 3 "/dev/$tgt_dev" | grep 'serial' | awk '{print $2}'`
tgt_size=`fdisk -l -u /dev/$tgt_dev | grep Disk | grep $tgt_dev | awk -F ',' '{ print $1}' | awk '{print $3$4}'`
tgt_free=`df -h -P | grep $tgt_mnt | awk {'print $4'}`
image_start_date=`date +"%A, %B %d, %Y"`
image_start_time=`date +"%H:%M"`
image_end_date=`ls -l -t $tgt_mnt/$evid_code/*.E* | head -1 | awk {'print $7'}`
image_end_time=`ls -l -t $tgt_mnt/$evid_code/*.E* | head -1 | awk {'print $8'}`
evid_hash=`cat $tgt_mnt/$evid_code/$evid_code.E01.txt | grep -i -A1 md5 | grep -i md5 | awk '{print $3}' | head -n1`
tgt_hash=`cat $tgt_mnt/$evid_code/$evid_code.E01.txt | grep -i -A1 md5 | grep -i md5 | awk '{print $3"\t"$5}' | tail -n1`
tgt_bytes=`cat $auditfile | grep copied | awk '{print $1}'`
tgt_sectors=`cat $auditfile | grep -A1 results | grep -A1 $tgt_mnt| grep sectors | awk '{print $1}'`
evid_count=`find /mnt/evidence -type f -print | wc -l`
tgt_count=`find /mnt/target_image -type f -print | wc -l`
evid_count2=`find /mnt/evidence2 -type f -print | wc -l`
tgt_count2=`find /mnt/target_image2 -type f -print | wc -l`
bkup_dev_model=`hdparm -I /dev/$bkup_dev | grep -i 'Model Number' | awk '{print $3" "$4" "$5" "$6}'`
bkup_dev_serial=`hdparm -I /dev/$bkup_dev | grep -i 'Serial Number' | awk '{print $3" "$4" "$5" "$6}'`
bkup_dev_firmware=`hdparm -I /dev/$bkup_dev | grep -i 'Firmware Revision' | awk '{print $3" "$4" "$5" "$6}'`
bkup_act_mnt=`df -h -P | grep $bkup_mnt | awk {'print $6'}`
bkup_scsi_vendor=`cat /proc/scsi/scsi | grep -A 1 "scsi$bkup_dev_id" | grep "Vendor" | awk -F ':' '{print $2}'`
bkup_scsi_model=`cat /proc/scsi/scsi | grep -A 1 "scsi$bkup_dev_id" | grep "Vendor" | awk -F ':' '{print $3}' | awk -F 'Rev' '{print $1}'`
bkup_scsi_serial=`lshw -C Disk | grep -A 3 "/dev/$bkup_dev" | grep 'serial' | awk '{print $2}'`
bkup_size=`fdisk -l -u /dev/$bkup_dev | grep Disk | grep $bkup_dev | awk -F ',' '{ print $1}' | awk '{print $3$4}'`
bkup_free=`df -h -P | grep $bkup_mnt | awk {'print $4'}`
image_start_date=`date +"%A, %B %d, %Y"`
image_start_time=`date +"%H:%M"`
image_end_date=`ls -l -t $tgt_mnt/$evid_code/*.E* | head -1 | awk {'print $7'}`
image_end_time=`ls -l -t $tgt_mnt/$evid_code/*.E* | head -1 | awk {'print $8'}`
copy_date=`date +"%A, %B %d, %Y"`
copy_time=`date +"%H:%M"`
evid_hash=`cat $tgt_mnt/$evid_code/$evid_code.E01.txt | grep -i -A1 md5 | grep -i md5 | awk '{print $3}' | head -n1`
tgt_hash=`cat $tgt_mnt/$evid_code/$evid_code.E01.txt | grep -i -A1 md5 | grep -i md5 | awk '{print $3}' | tail -n1`
bkup_hash=`ewfinfo $bkup_mnt/$evid_code/$evid_code.E01 | grep -i -A1 md5 | awk '{print $2}' | head -n1`
tgt_bytes=`cat $auditfile | grep copied | awk '{print $1}'`
bkup_bytes=`cat $auditfile | grep copied | awk '{print $1}'`
tgt_sectors=`cat $auditfile | grep -A1 results | grep -A1 $tgt_mnt| grep sectors | awk '{print $1}'`
bkup_sectors=`cat $auditfile | grep -A1 results | grep -A1 $bkup_mnt| grep sectors | awk '{print $1}'`
evid_count=`find /mnt/evidence -type f -print | wc -l`
tgt_count=`find /mnt/target_image -type f -print | wc -l`
bkup_count=`find /mnt/target_image -type f -print | wc -l`
evid_count2=`find /mnt/evidence2 -type f -print | wc -l`
tgt_count2=`find /mnt/target_image2 -type f -print | wc -l`
bkup_count2=`find /mnt/target_image2 -type f -print | wc -l`
copy_date=`date +"%A, %B %d, %Y"`
copy_time=`date +"%H:%M"`
pst_count=`grep "PST|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
pst_size=`grep "PST|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
ost_count=`grep "OST|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
ost_size=`grep "OST|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
dbx_count=`grep "DBX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
dbx_size=`grep "DBX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
nsf_count=`grep "NSF|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
nsf_size=`grep "NSF|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
doc_count=`grep "DOC|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
doc_size=`grep "DOC|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
docx_count=`grep "DOCX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
docx_size=`grep "DOCX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
xls_count=`grep "XLS|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
xls_size=`grep "XLS|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
xlsx_count=`grep "XLSX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
xlsx_size=`grep "XLSX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
ppt_count=`grep "PPT|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
ppt_size=`grep "PPT|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
pptx_count=`grep "PPTX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
pptx_size=`grep "PPTX|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
pdf_count=`grep "PDF|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $2'}`
pdf_size=`grep "PDF|" $tgt_mnt/$evid_code/$evid_code.filetype_count.pipe | awk -F "|" {'print $3'}`
